### ISSUE TITLE
Extract not working 

### ISSUE THREAD

**Issue by LeBressan** [coderaiser/node-onezip#3]
Hi,
I am doing an app that is compressing in C# and extracting the content in electron (JS).

The extract is not working for any content that has been compressed to zip using the MS C# lib System.IO.Compression with ZipFile.CreateFromDirectory(pathFolderToZip, Destination.zip)

Not sure if this is a security, encoding or a mime type issue. 

Hope this help to make the module better.

Kind regards,
C

**Comment by coderaiser** [comment]
What error do you have while extracting? Could you please try to use [yauzl](https://github.com/thejoshwolfe/yauzl), is it works for you?

**Comment by LeBressan** [comment]
So I am using "extract-zip" module now, and everything works fine. 

I was getting the event "extracting started" and then I get a 
Error: ENOENT: No such file or directory, open "path/to/file.exe" 
It is like the extract is looking for directory instead of files, but this only happened with zip files I was creating from a C# app. Using 7zip for example (on the same directory than my C# app), your module worked fine.. So i am a bit confused what could be the error.

Hope this help.

**Comment by coderaiser** [comment]
Could you please attach `zip` file?

**Comment by coderaiser** [comment]
Closed due to absence of archive example.
