### ISSUE TITLE
Unzip error on Windows

### ISSUE THREAD

**Issue by Axel0087** [coderaiser/node-onezip#7]
It appears that there is an issue with unzipping on windows if the zipfile consists of both a folder and other files/folders. I've not been able to replicate this issue on neither linux nor mac.

I've attached two folders with issues. zip_folders.zip consists of two folders folder and folder2 containing file and file2 respectively. Running  `λ npx onezip -x ~/zip_folders.zip` gives the error `ENOENT: no such file or directory, open 'C:\path_to_folder\folder\file.txt'`.

zip_error.zip consists of folder and file1 zipped together, with folder containing file2. Running `λ npx onezip -x ~/zip_error.zip` gives the error `ENOENT: no such file or directory, open 'C:\path_to_folder\folder\file2.txt'`.

[zip_folders.zip](https://github.com/coderaiser/node-onezip/files/5481242/zip_folders.zip)
[zip_error.zip](https://github.com/coderaiser/node-onezip/files/5481234/zip_error.zip)

**Comment by coderaiser** [comment]
Thanks a log, this bugs reproduced on linux as well :). Fixed with b9146d8. Landed in [v5.0.0](https://github.com/coderaiser/node-onezip/releases/tag/v5.0.0) 🎉 .

Is it works for you?
