### ISSUE TITLE
Request to update the glob package v7.0.0 to latest

### ISSUE THREAD

**Issue by ishanuda** [coderaiser/node-onezip#9]
Hi,
There is a vulnerable package i.e. **inflight** used by the **glob** package which has been reported in the following issue.
[Using vulnerable package inflight](https://github.com/isaacs/node-glob/issues/574).

The **glob** no longer is using the aforementioned package and further information can be found with the following link.

[Memory leak in **inflight** dependency](https://github.com/isaacs/node-glob/issues/573)

Could you please update the **glob** package to the latest version.

Thank you very much.

**Comment by coderaiser** [comment]
Make PR and I merge

**Comment by ishanuda** [comment]
Thank you

**Comment by coderaiser** [comment]
Just fixed in [v6](https://github.com/coderaiser/node-onezip/releases/tag/v6.0.0) is it works for you?

**Comment by ishanuda** [comment]
Thank you for the update.

I will check and confirm here.
FIY: I also see that the package "yauzl" and "yazl" is outdated.

**Comment by coderaiser** [comment]
Only Node >= v18 supported

**Comment by coderaiser** [comment]
FYI: I also see that the package "yauzl" and "yazl" is outdated.

What latest versions of this packages?

**Comment by ishanuda** [comment]
Hi, 
Followings are the new releases

"yauzl": "^2.10.0",
https://www.npmjs.com/package/yauzl?activeTab=versions


"yazl": "^2.5.1"
https://www.npmjs.com/package/yazl?activeTab=versions

Thanks.

**Comment by coderaiser** [comment]
So why do you tell me that yauzl" and "yazl" is outdated?

**Comment by ishanuda** [comment]
HI,
I see the aforementioned libraries are used in the library. Isn't it good to update the outdated libraries?

**Comment by coderaiser** [comment]
They are up to date, you always install latest versions, since npm uses https://semver.org/
